### hello-go/.github/workflows/build.yml
name: go-ci

on:
  push:
    branches: [main]

jobs:
  call-go-ci:
    uses: nirajan-devops/ci-workflows/.github/workflows/Go.yml@main
    with:
      go-version: '1.24'     # must exist as an `inputs` key in Go.yml
      context: .             # same here (or remove if you kept the default)
