name: Deploy React App via Docker

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t go-Hello-world .

  
      - name: Save Docker image to tar
        run: docker save go-Hello-world -o go-Hello-world.tar

      - name: Copy image to EC2 via SCP
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "Go-Hello-world.tar"
          target: "/home/${{ secrets.USERNAME }}/"
          tar_dereference: false
          strip_components: false
          overwrite: true
          rm: false

      - name: Install Docker and Deploy on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Install Docker if it's not present
            if ! command -v docker &> /dev/null; then
              echo "Installing Docker..."
              sudo apt update
              sudo apt install -y docker.io
              sudo systemctl enable docker
              sudo systemctl start docker
            fi

            cd /home/${{ secrets.USERNAME }}

            echo "Loading Docker image..."
            ls -lh go-Hello-world.tar
            sudo docker load -i go-Hello-world.tar

            echo "Stopping existing container if running..."
            sudo docker stop go-Hello-world || true
            sudo docker rm go-Hello-world || true

            echo "Running new go-Hello-world container..."
            sudo docker run -d -p 8080:8080 --name go-Hello-world go-Hello-world
